// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChangeSet struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Checksum             string   `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Format               string   `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeSet) Reset()         { *m = ChangeSet{} }
func (m *ChangeSet) String() string { return proto.CompactTextString(m) }
func (*ChangeSet) ProtoMessage()    {}
func (*ChangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{0}
}

func (m *ChangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeSet.Unmarshal(m, b)
}
func (m *ChangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeSet.Marshal(b, m, deterministic)
}
func (m *ChangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeSet.Merge(m, src)
}
func (m *ChangeSet) XXX_Size() int {
	return xxx_messageInfo_ChangeSet.Size(m)
}
func (m *ChangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeSet proto.InternalMessageInfo

func (m *ChangeSet) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ChangeSet) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *ChangeSet) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *ChangeSet) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ChangeSet) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Change struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string     `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Author               string     `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Comment              string     `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Timestamp            int64      `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChangeSet            *ChangeSet `protobuf:"bytes,6,opt,name=changeSet,proto3" json:"changeSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}
func (*Change) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{1}
}

func (m *Change) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Change.Unmarshal(m, b)
}
func (m *Change) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Change.Marshal(b, m, deterministic)
}
func (m *Change) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Change.Merge(m, src)
}
func (m *Change) XXX_Size() int {
	return xxx_messageInfo_Change.Size(m)
}
func (m *Change) XXX_DiscardUnknown() {
	xxx_messageInfo_Change.DiscardUnknown(m)
}

var xxx_messageInfo_Change proto.InternalMessageInfo

func (m *Change) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Change) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Change) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Change) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Change) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Change) GetChangeSet() *ChangeSet {
	if m != nil {
		return m.ChangeSet
	}
	return nil
}

type ChangeLog struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Change               *Change  `protobuf:"bytes,2,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeLog) Reset()         { *m = ChangeLog{} }
func (m *ChangeLog) String() string { return proto.CompactTextString(m) }
func (*ChangeLog) ProtoMessage()    {}
func (*ChangeLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{2}
}

func (m *ChangeLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeLog.Unmarshal(m, b)
}
func (m *ChangeLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeLog.Marshal(b, m, deterministic)
}
func (m *ChangeLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeLog.Merge(m, src)
}
func (m *ChangeLog) XXX_Size() int {
	return xxx_messageInfo_ChangeLog.Size(m)
}
func (m *ChangeLog) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeLog.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeLog proto.InternalMessageInfo

func (m *ChangeLog) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ChangeLog) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

type CreateRequest struct {
	Change               *Change  `protobuf:"bytes,1,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{3}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

type CreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{4}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

type UpdateRequest struct {
	Change               *Change  `protobuf:"bytes,1,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{6}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

type DeleteRequest struct {
	Change               *Change  `protobuf:"bytes,1,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{8}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type ReadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{9}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ReadResponse struct {
	Change               *Change  `protobuf:"bytes,1,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{10}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

type SearchRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{11}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SearchRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *SearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchResponse struct {
	Configs              []*Change `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{12}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetConfigs() []*Change {
	if m != nil {
		return m.Configs
	}
	return nil
}

type WatchRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchRequest) Reset()         { *m = WatchRequest{} }
func (m *WatchRequest) String() string { return proto.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()    {}
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{13}
}

func (m *WatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchRequest.Unmarshal(m, b)
}
func (m *WatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchRequest.Marshal(b, m, deterministic)
}
func (m *WatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchRequest.Merge(m, src)
}
func (m *WatchRequest) XXX_Size() int {
	return xxx_messageInfo_WatchRequest.Size(m)
}
func (m *WatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchRequest proto.InternalMessageInfo

func (m *WatchRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type WatchResponse struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChangeSet            *ChangeSet `protobuf:"bytes,2,opt,name=changeSet,proto3" json:"changeSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WatchResponse) Reset()         { *m = WatchResponse{} }
func (m *WatchResponse) String() string { return proto.CompactTextString(m) }
func (*WatchResponse) ProtoMessage()    {}
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{14}
}

func (m *WatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchResponse.Unmarshal(m, b)
}
func (m *WatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchResponse.Marshal(b, m, deterministic)
}
func (m *WatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchResponse.Merge(m, src)
}
func (m *WatchResponse) XXX_Size() int {
	return xxx_messageInfo_WatchResponse.Size(m)
}
func (m *WatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WatchResponse proto.InternalMessageInfo

func (m *WatchResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WatchResponse) GetChangeSet() *ChangeSet {
	if m != nil {
		return m.ChangeSet
	}
	return nil
}

type AuditLogRequest struct {
	// from unix timestamp
	From int64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	// to unix timestamp
	To int64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	// limit number items
	Limit int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// the offset
	Offset int64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// reverse the order
	Reverse              bool     `protobuf:"varint,5,opt,name=reverse,proto3" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditLogRequest) Reset()         { *m = AuditLogRequest{} }
func (m *AuditLogRequest) String() string { return proto.CompactTextString(m) }
func (*AuditLogRequest) ProtoMessage()    {}
func (*AuditLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{15}
}

func (m *AuditLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditLogRequest.Unmarshal(m, b)
}
func (m *AuditLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditLogRequest.Marshal(b, m, deterministic)
}
func (m *AuditLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditLogRequest.Merge(m, src)
}
func (m *AuditLogRequest) XXX_Size() int {
	return xxx_messageInfo_AuditLogRequest.Size(m)
}
func (m *AuditLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuditLogRequest proto.InternalMessageInfo

func (m *AuditLogRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *AuditLogRequest) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *AuditLogRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AuditLogRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *AuditLogRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

type AuditLogResponse struct {
	Changes              []*ChangeLog `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AuditLogResponse) Reset()         { *m = AuditLogResponse{} }
func (m *AuditLogResponse) String() string { return proto.CompactTextString(m) }
func (*AuditLogResponse) ProtoMessage()    {}
func (*AuditLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{16}
}

func (m *AuditLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditLogResponse.Unmarshal(m, b)
}
func (m *AuditLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditLogResponse.Marshal(b, m, deterministic)
}
func (m *AuditLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditLogResponse.Merge(m, src)
}
func (m *AuditLogResponse) XXX_Size() int {
	return xxx_messageInfo_AuditLogResponse.Size(m)
}
func (m *AuditLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuditLogResponse proto.InternalMessageInfo

func (m *AuditLogResponse) GetChanges() []*ChangeLog {
	if m != nil {
		return m.Changes
	}
	return nil
}

func init() {
	proto.RegisterType((*ChangeSet)(nil), "ChangeSet")
	proto.RegisterType((*Change)(nil), "Change")
	proto.RegisterType((*ChangeLog)(nil), "ChangeLog")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*WatchRequest)(nil), "WatchRequest")
	proto.RegisterType((*WatchResponse)(nil), "WatchResponse")
	proto.RegisterType((*AuditLogRequest)(nil), "AuditLogRequest")
	proto.RegisterType((*AuditLogResponse)(nil), "AuditLogResponse")
}

func init() { proto.RegisterFile("config/config.proto", fileDescriptor_cc332a44e926b360) }

var fileDescriptor_cc332a44e926b360 = []byte{
	// 586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x9b, 0xa4, 0x4d, 0xdb, 0x69, 0x9b, 0x16, 0x83, 0x50, 0x14, 0x21, 0x28, 0x16, 0x48,
	0x15, 0x48, 0xde, 0xdd, 0xee, 0x85, 0x2b, 0xea, 0x5e, 0x90, 0xf6, 0xe4, 0x15, 0xe2, 0x6c, 0x12,
	0xb7, 0x8d, 0xd8, 0xd4, 0x25, 0x71, 0xb9, 0xf1, 0x00, 0xbc, 0x08, 0x0f, 0xc2, 0x93, 0x21, 0xff,
	0xdb, 0x26, 0x11, 0xbb, 0x6c, 0x4f, 0xf5, 0xd8, 0x33, 0xdf, 0x7c, 0x1d, 0xff, 0x1c, 0x78, 0x9a,
	0x8a, 0xdd, 0x3a, 0xdf, 0x9c, 0x99, 0x1f, 0xb2, 0x2f, 0x85, 0x14, 0xf8, 0x97, 0x07, 0xc3, 0xd5,
	0x96, 0xed, 0x36, 0xfc, 0x86, 0x4b, 0x84, 0xa0, 0x9b, 0x31, 0xc9, 0x62, 0x6f, 0xee, 0x2d, 0xc6,
	0x54, 0xaf, 0x51, 0x02, 0x83, 0x74, 0xcb, 0xd3, 0x6f, 0xd5, 0xa1, 0x88, 0xfd, 0xb9, 0xb7, 0x18,
	0xd2, 0xbb, 0x18, 0x3d, 0x87, 0x70, 0x2d, 0xca, 0x82, 0xc9, 0x38, 0xd0, 0x27, 0x36, 0x52, 0xfb,
	0x95, 0x38, 0x94, 0x29, 0x8f, 0xbb, 0x66, 0xdf, 0x44, 0xe8, 0x05, 0x0c, 0x65, 0x5e, 0xf0, 0x4a,
	0xb2, 0x62, 0x1f, 0xf7, 0xe6, 0xde, 0x22, 0xa0, 0xc7, 0x0d, 0xfc, 0xdb, 0x83, 0xd0, 0x78, 0x41,
	0x11, 0xf8, 0x79, 0xa6, 0x6d, 0x0c, 0xa9, 0x9f, 0x67, 0xca, 0xd8, 0x9e, 0xc9, 0xad, 0x35, 0xa0,
	0xd7, 0xaa, 0x09, 0x3b, 0xc8, 0xad, 0x28, 0x5d, 0x73, 0x13, 0xa1, 0x18, 0xfa, 0xa9, 0x28, 0x0a,
	0xbe, 0x93, 0xb6, 0xbb, 0x0b, 0x1f, 0x6e, 0x8f, 0x16, 0x30, 0x4c, 0xdd, 0x24, 0xe2, 0x70, 0xee,
	0x2d, 0x46, 0x4b, 0x20, 0x77, 0xb3, 0xa1, 0xc7, 0x43, 0x7c, 0xe5, 0x66, 0x76, 0x2d, 0x36, 0xda,
	0x46, 0x2a, 0x73, 0xb1, 0xb3, 0x76, 0x6d, 0x84, 0x5e, 0x41, 0x68, 0x2a, 0xb4, 0xe9, 0xd1, 0xb2,
	0x6f, 0xb5, 0xa8, 0xdd, 0xc6, 0xe7, 0x30, 0x59, 0x95, 0x9c, 0x49, 0x4e, 0xf9, 0xf7, 0x03, 0xaf,
	0x64, 0xad, 0xc2, 0xfb, 0x77, 0xc5, 0x0c, 0x22, 0x57, 0x51, 0xed, 0xc5, 0xae, 0xd2, 0x1a, 0x9f,
	0xf7, 0xd9, 0x89, 0x1a, 0xae, 0xe2, 0xa8, 0x71, 0xc5, 0x6f, 0xf9, 0x69, 0x1a, 0xae, 0xc2, 0x6a,
	0x5c, 0xc0, 0x88, 0x72, 0x96, 0x39, 0x85, 0x47, 0x5c, 0x1f, 0x3e, 0x83, 0xb1, 0x29, 0x31, 0x12,
	0xff, 0xef, 0xca, 0x61, 0x72, 0xc3, 0x59, 0x99, 0x6e, 0xef, 0xeb, 0x72, 0x04, 0xc2, 0x6f, 0x00,
	0xf1, 0x0c, 0x7a, 0xb7, 0x79, 0x91, 0x1b, 0x48, 0x03, 0x6a, 0x02, 0x95, 0x2d, 0xd6, 0xeb, 0x8a,
	0x1b, 0x4a, 0x02, 0x6a, 0x23, 0x7c, 0x09, 0x91, 0x6b, 0x63, 0x9d, 0xbd, 0x56, 0x40, 0xa9, 0x37,
	0x53, 0xc5, 0xde, 0x3c, 0xa8, 0x5b, 0x73, 0xfb, 0xf8, 0x25, 0x8c, 0xbf, 0x30, 0x79, 0xaf, 0x35,
	0xfc, 0x09, 0x26, 0xf6, 0xdc, 0x6a, 0xb6, 0xbd, 0x37, 0xe0, 0xf3, 0x1f, 0x82, 0xef, 0x27, 0x4c,
	0x3f, 0x1e, 0xb2, 0x5c, 0x5e, 0x8b, 0x8d, 0xeb, 0x86, 0xa0, 0xbb, 0x2e, 0x45, 0xa1, 0xe5, 0x02,
	0xaa, 0xd7, 0xaa, 0x81, 0x14, 0x5a, 0x29, 0xa0, 0xbe, 0x14, 0xa7, 0x0d, 0x41, 0xbd, 0xa1, 0x92,
	0xff, 0xe0, 0x65, 0xc5, 0xf5, 0x3b, 0x19, 0x50, 0x17, 0xe2, 0x0f, 0x30, 0x3b, 0xb6, 0xb7, 0x7f,
	0xe6, 0x0d, 0xf4, 0x8d, 0x3f, 0x37, 0x20, 0x67, 0x5d, 0x25, 0xb9, 0xa3, 0xe5, 0x1f, 0x1f, 0xc2,
	0x95, 0x9e, 0x17, 0x7a, 0x0f, 0xa1, 0x01, 0x19, 0x45, 0xa4, 0xf1, 0x06, 0x92, 0x29, 0x69, 0x11,
	0xde, 0x51, 0xc9, 0x86, 0x58, 0x14, 0x91, 0x06, 0xec, 0xc9, 0x94, 0xb4, 0x50, 0xd6, 0xc9, 0x06,
	0x4d, 0x14, 0x91, 0x06, 0xd5, 0xc9, 0x94, 0xb4, 0x98, 0xd5, 0xc9, 0xe6, 0xaa, 0x51, 0x44, 0x1a,
	0x68, 0x25, 0x53, 0xd2, 0x64, 0x00, 0x77, 0xd0, 0x5b, 0xe8, 0x2a, 0x5e, 0xd1, 0x98, 0xd4, 0x48,
	0x4f, 0x26, 0xa4, 0x0e, 0x31, 0xee, 0xa0, 0x0b, 0x18, 0xb8, 0xf9, 0xa0, 0x19, 0x69, 0xdd, 0x54,
	0xf2, 0x84, 0xb4, 0x87, 0x87, 0x3b, 0xe8, 0x1d, 0xf4, 0x34, 0x1c, 0x68, 0x42, 0xea, 0x10, 0x25,
	0x11, 0x69, 0x30, 0x83, 0x3b, 0xe7, 0xde, 0xd7, 0x50, 0x7f, 0xb6, 0x2f, 0xff, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x71, 0xe4, 0x74, 0x9f, 0xcd, 0x05, 0x00, 0x00,
}
